{{-- resources/views/admin/users/create-doctor.blade.php --}}
@extends('layouts.app')
@section('title','Add Doctor')
@section('page-title','Add New Doctor')
@section('sidebar-nav')@include('admin.partials.nav')@endsection
@section('content')
<div style="max-width:600px;">
  <div class="card">
    <div class="card-header"><div class="card-title">🩺 Add New Doctor</div><a href="{{ route('admin.doctors') }}" class="btn btn-out btn-sm">← Back</a></div>
    <div class="alert alert-b" style="margin-bottom:20px;"><span>ℹ️</span><span style="font-size:13px;">Doctors do <strong>not</strong> have email/password. They log in using their Staff Code + a session code generated by admin for each school visit.</span></div>
    <form method="POST" action="{{ route('admin.doctors.store') }}">
      @csrf
      <div class="form-grid">
        <div class="form-group"><label class="form-label">Full Name <span class="req">*</span></label><input type="text" name="name" class="form-input" placeholder="Dr. Priya Kapoor" value="{{ old('name') }}" required/></div>
        <div class="form-group">
          <label class="form-label">Staff Code <span class="req">*</span></label>
          <input type="text" name="staff_code" class="form-input" placeholder="CMF-DOC-0021" value="{{ old('staff_code','CMF-DOC-'.str_pad(rand(1,999),4,'0',STR_PAD_LEFT)) }}" required style="text-transform:uppercase;"/>
          <div class="form-hint">Must be unique. Format: CMF-DOC-XXXX</div>
        </div>
      </div>
      <div class="form-grid">
        <div class="form-group"><label class="form-label">Phone</label><input type="tel" name="phone" class="form-input" placeholder="+91 98765 43210" value="{{ old('phone') }}"/></div>
        <div class="form-group"><label class="form-label">Primary School (optional)</label><input type="text" name="school_name" class="form-input" placeholder="DPS Vadodara" value="{{ old('school_name') }}"/></div>
      </div>
      <button type="submit" class="btn btn-b btn-lg btn-full">Create Doctor Account →</button>
    </form>
  </div>
</div>
@endsection
